<div class="modal fade" id="terms-and-conditions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Terms and Conditions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5><strong>General Terms and Conditions</strong></h5>
          <h5><strong>1. The Scope of the Application</strong></h5>
          <p>These Terms and Conditions apply to the use of the emporium-collection™ websites and all bookings of hotels via the reservation system of emporium-collection.com applications, Eisolzriederstrasse 12, 80999 München</p>
          <h5><strong>2. General Use Of The Emporium-Collection™ Websites</strong></h5>
          <p>On the emporium-collection™ websites you can search for the availability and rates of hotels and rooms of your choice at dates defined by you for a specific number of travelers. emporium-collection™ reserves the right to discontinue its websites at any time.</p>
          <p><strong><label>2.1. Hotel Content and Categories</label></strong></p>
          <p>All information about a hotel and the descriptions of a hotel are based on the hotel's own assessment. All content about a hotel that is displayed on the emporium-collection™ websites is provided to emporium-collection™ by the respective hotel and emporium-collection™ acts as the content provider for the hotel only and is thus not responsible for the content, any omissions or typographical errors referring to a hotel. As far as displayed on the emporium-collection™ websites the internationally used hotel classification into stars offers noncommittal information about the hotel's standard, in consideration of self-assessment by the hotel which was provided by the hotel.</p>
          <p><strong><label>2.2.Prices and Taxes</label></strong></p>
          <p>All prices displayed on the emporium-collection™ websites are current, day prices, shown in the name of the individual hotel and are valid for all bookings made via the reservation system of emporium-collection™ as described below in section C. All prices have been provided by the hotel and emporium-collection™ acts as content provider for the hotel only and is thus not responsible for any errors of prices referring to a hotel.</p>
          <p>For Germany, prices displayed on the emporium-collection™ websites always include service charges and VAT. For other countries regulations and rules regarding taxes differ. Please note, that a visitor's tax might apply in certain locations. In some countries, a local tax and/or a service charge is levied on the travel price or room rate. The amount of this tax changes all the time and can’t generally be estimated but requires specific information like the exact period of a stay, a number of people staying, etc. to be calculated. Thus any information regarding such taxes is always noncommittal, as long as you do not enter specific travel dates. When you make a booking as per below Section C. the applicable taxes will, in any case, be displayed.<br />Complimentary room upgrades and late check-outs as part of the emporium-collection™ community benefits are subject to availability. Hotels reserve the right to discontinue the offer at any time.<br />Obvious errors and mistakes (including misprints) are not binding</p>
          <h5><strong>3. Registration</strong></h5>
          <p>You can register on the emporium-collection™ websites. If you voluntarily provide personal data as part of such registration, it will be used to pre-fill the personal details form upon making a booking, and/or be used to provide you with more refined topics in our communications, should you have opted into any of our newsletters. You can cancel your registration with emporium-collection™ at any time. Please send an according to e-mail to legal@emporium-collection.com</p>
          <h5><strong>4. Auto Login</strong></h5>
          <p>You may choose to stay logged in on our emporium-collection™ websites. We will then will store your login information in a cookie, i.e. a small text file, on your computer so that you do not have to authenticate upon return to our websites but will be automatically logged in ("auto login"). The cookie and thereby the auto log in expires automatically after 60 days. Further information about other cookies is available in our privacy policy.</p>
          <h5><strong>5. Accommodation Contract And Payment</strong></h5>
          <p>If you make a booking through emporium-collection™ reservation system the accommodation contract comes into effect between you and the hotel of your choice. You pay the confirmed price directly to the hotel. Any claims and obligations out of the accommodation contract only exist between you and the hotel chosen by you. emporium-collection™ does not enter into the contract with you about the accommodation. Rates available and any booking made via the emporium-collection™ reservation system can’t be combined with other offers or promotions.<br />Bookings take place according to the best and currently lowest emporium-collection™ day price in each case. This price is submitted directly by the hotel for the arrival date chosen and is shown in the name of the hotel. Available emporium-collection™ last-minute, seasonal, weekend or special prices will be considered automatically during the booking.</p>
          <p><strong><label>5.1. Making a Booking</label></strong></p>
          <p>If you want to make a booking after your availability search, you will have to fill in personal details about you and your credit card details. The credit card details are required to guarantee your booking, the charges will be made by the hotel. If you are logged in to your account the personal details will be pre-filled. By clicking the button “CONFIRM REGISTRATION". Charged upon arrival” you make a binding offer to book the selected room. Prior to making the booking, i.e. prior to clicking the button, you can identify any errors in the data you have provided directly on the website and correct them by clicking “edit” next to the hotel and room description.<br />Every booking offer you make will be forwarded to the corresponding hotel and any messages from the hotel to you, particularly the confirmation of your booking will be forwarded to you via emporium-collection™ as the carrier of the message. emporium-collection™ shall have a relationship with you and the hotel only as an independent third party and shall not be a partner, trustee, representative or sub-contractor either for you or the hotel. Also, the hotel shall not be a subcontractor or vicarious agent of emporium-collection™. As soon as you receive the booking confirmation from the hotel via the emporium-collection™ reservation system, you have entered into a contract with the hotel and the booking is binding. You will receive a customer booking reference number together with the confirmation of your booking. The use of the emporium-collection™ reservation system is free of charge for you. Bookings are not transferable to any other person and can not be transferred or exchanged for cash or credit</p>
          <p><strong><label>5.2. Cancelations</label></strong></p>
          <p>You do not have a statutory right of withdrawal from booking as per Sec. 312 g para 2 no. 9 of the German Civil Code (BGB).<br />However, a hotel may voluntarily offer a right to cancel or change a booking for selected offers in the emporium-collection™ reservation system. Any such right will be displayed in the order form before you make your order. Where a hotel voluntarily grants such right to cancel or to change a booking in the emporium-collection™ reservation system, any such changes and cancellations have to be carried out via the emporium-collection™ online system or via the emporium-collection™ reservation number (see <a href="http://www.emporium-collection.com/">www.emporium-collection.com</a>) to be fully effective. In case of a change or cancellation carried out directly at the hotel, emporium-collection™ cannot provide any information concerning possible discrepancies concerning the date of the cancellation or the fact of cancellation as such</p>
          <p><strong><label>5.3.Storing and Accessibility of the Contract</label></strong></p>
          <p>We will store your booking information and the terms and conditions applicable to the booking (collectively referred to as “contract”). The current version of our terms and conditions is available for you at https://www.emporium-collection™.com/terms-and-conditions. You can access your booking information also after the booking via your emporium-collection™ account.</p>
          <h5><strong>6. Liability</strong></h5>
          <p>- In case of intent or gross negligence on part of emporium-collection™ or by its agents or vicarious agents in performance emporium-collection™ shall be liable according to the provisions of applicable law. The same applies in case of breach of an essential contractual obligation (an obligation that must be fulfilled to enable the correct execution of the agreement and which the customer may usually trust and may trust that it will be fulfilled); however, to the extent such breach was unintentionally emporium-collection™ liability shall be limited to typical damages foreseeable under the contract.<br />emporium-collection™ liability for culpable damage to life, body or health as well as our liability under the Product Liability Act shall remain unaffected.<br />Any liability not expressly provided for above shall be disclaimed. Particularly emporium-collection™ disclaims any liability for the reproduction of this website through a third-party website or access to this website obtained through a third-party website or any user’s home page, which reproduction misstates or omits any of the information or limitations and conditions on the room rates and products offered through this website</p>
          <h5><strong>7. Intellectual Property</strong></h5>
          <p>All trademarks (including, but not limited to, the emporium-collection™ trademark, reproductions of emporium-collection™ logo), copyright, database rights and other intellectual property rights in the materials on this website (as well as the organisation and layout of this website) together with the underlying software code are owned either directly by emporium-collection™ or by it's licensors. Without emporium-collection™ prior written permission, you may not copy, modify, alter, publish, broadcast, distribute, sell or transfer any material on this website or the underlying software code whether in whole or in part. However, the contents of this website may be downloaded, printed or copied for your personal non-commercial use. The emporium-collection™ logo is a registered trademark and is the property of emporium-collection™ and may not be used or reproduced without emporium-collection™ express written permission.<br />Data transfer into other data carriers, even part of it, or it's used for a different purpose to the one designated here, is only permitted with the explicit permission of emporium-collection™, except where explicitly permitted by applicable law.</p>
          <h5><strong>8. Miscellaneous</strong></h5>
          <p>The invalidity or unenforceability of any of these Terms and Conditions shall not affect, impair or invalidate any of the remaining terms and conditions.</p>
          <h5><strong>9. Governing Law and Place of Jurisdiction</strong></h5>
          <p>All legal relations between you and emporium-collection™ shall exclusively be governed by the laws of the Federal Republic of Germany. If you act as a consumer and have entered into a contract while residing in another country, the application of the mandatory law of such country shall not be affected by the previous sentence.<br />If you are a trader or an entity of public law, the competent courts in Munich shall have jurisdiction for all disputes. emporium-collection™ shall, however, also be entitled to sue you at your general venue.</p>
          <p>The website is owned and operated by emporium-collection™. The website can be used, registrations and bookings can be made and in the English language.</p>
          <p><em>Plattform of The European Commission for online dispute resolution: <a href="http://www.ec.europa.eu/consumers">www.ec.europa.eu/consumers/odr/</a></em></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Accept!</button>
      </div>
    </div>
  </div>
</div>